version: 1.0.{build}
image: 
  - Visual Studio 2019 Preview
  - Ubuntu1804

install:

# Windows instructions
  - ps: Write-Host "I'm windows!"
  
  # Install vagrant from separate script as it throws 3010 error code to make ya reboot.
  - ps: cd $env:APPVEYOR_BUILD_FOLDER/ci-scripts/windows/
  - ps: powershell ./try-install-vagrant.ps1

  - ps: choco install -y ruby
  - ps: choco install -y virtualbox
  - ps: choco install -y packer

  # Build all missing boxes.
  - ps: cd $env:APPVEYOR_BUILD_FOLDER/packer
  - ps: packer build ubuntu-mysql.json
  - ps: packer build ubuntu-storage.json
  - ps: packer build ubuntu-webserver.json
  
  # Vagrant up!
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  - ps: vagrant up

  
# Linux instructions
  - sh: echo "I'm Linux!"
  
  - sh: sudo apt update
  
  - sh: cd ${APPVEYOR_BUILD_FOLDER}/
  - sh: sh ci-scripts/linux/install-deps.sh
  
  # Build all missing boxes.
  - sh: cd ${APPVEYOR_BUILD_FOLDER}/packer
  - sh: packer build ubuntu-mysql.json
  - sh: packer build ubuntu-storage.json
  - sh: packer build ubuntu-webserver.json
  
  # Vagrant up!
  - sh: cd ${APPVEYOR_BUILD_FOLDER}/
  - sh: vagrant up