version: 1.0.{build}
image: 
  - Visual Studio 2019 Preview
  - Ubuntu1804

install:

# Windows instructions
  - ps: Write-Host "I'm windows!"

  - ps: choco install -y ruby virtualbox packer vagrant
  
  - ps: cd %APPVEYOR_BUILD_FOLDER%
  
  # Build all missing boxes.
  - ps: cd %APPVEYOR_BUILD_FOLDER%/packer
  - ps: packer build ubuntu-mysql.json
  - ps: packer build ubuntu-storage.json
  - ps: packer build ubuntu-webserver.json
  
  # Vagrant up!
  - sh: cd ${APPVEYOR_BUILD_FOLDER}/
  - sh: vagrant up
# Linux instructions
  - sh: echo "I'm Linux!"
  
  - sh: sudo apt update
  
  # Install normal deps
  - sh: sudo apt -y install ruby
  
  # Purge existing vbox for proper installation
  - sh: sudo apt autoremove virtualbox-dkms
  
  # Install VirtualBox.
  - sh: sudo apt -y install build-essential linux-headers-`uname -r` dkms virtualbox-dkms

  # Install Vagrant.
  - sh: sudo apt -y install vagrant virtualbox

  # Pre-accept virtualbox-ext-pack license.
  - sh: echo virtualbox-ext-pack virtualbox-ext-pack/license select true | sudo debconf-set-selections
  
  # Install virtualbox-ext-pack
  - sh: sudo apt -y install virtualbox-ext-pack
  
  # Build all missing boxes.
  - sh: cd ${APPVEYOR_BUILD_FOLDER}/packer
  - sh: packer build ubuntu-mysql.json
  - sh: packer build ubuntu-storage.json
  - sh: packer build ubuntu-webserver.json
  
  # Vagrant up!
  - sh: cd ${APPVEYOR_BUILD_FOLDER}/
  - sh: vagrant up