image: ubuntu

install:
  - echo "Potato!"
  
  - sudo apt update
  
  # Install normal deps
  - sudo apt -y install ruby
  
  # Purge existing vbox for proper installation
  - sudo apt autoremove virtualbox-dkms
  
  # Install VirtualBox.
  - sudo apt -y install build-essential linux-headers-`uname -r` dkms virtualbox-dkms

  # Install Vagrant.
  - sudo apt -y install vagrant virtualbox

  # Pre-accept virtualbox-ext-pack license.
  - echo virtualbox-ext-pack virtualbox-ext-pack/license select true | sudo debconf-set-selections
  
  # Install virtualbox-ext-pack
  - sudo apt -y install virtualbox-ext-pack
  
  # Build all missing boxes.
  - cd ${APPVEYOR_BUILD_FOLDER}/packer
  - packer build ubuntu-mysql.json
  - packer build ubuntu-storage.json
  - packer build ubuntu-webserver.json
  
  # Vagrant up!
  - cd ${APPVEYOR_BUILD_FOLDER}/
  - vagrant up
  